openapi: 3.0.0
info:
  title: 'E-Ticket API'
  version: '1.0'
paths:
  /confirmationBooking:
    post:
      tags:
        - Réservation
      operationId: a700cfe5e30e5057e2f992c56cdd75f6
      responses:
        '200':
          description: "Confirmation d'une réservation"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Booking'
  /createBooking:
    post:
      tags:
        - Réservation
      operationId: 08d7e2f88e98d683fe387a1a1e604cd3
      responses:
        '200':
          description: "Création d'une réservation de ticket"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Booking'
  /infrastructures/Api/Events/createEvent.php:
    post:
      tags:
        - Evenements
      summary: "La création d'un évènement"
      operationId: 7257c6b26358364493b53dc9766ecfc6
      requestBody:
        content:
          multipart/form-data:
            schema:
              properties:
                name:
                  type: string
                edate:
                  type: string
                etime:
                  type: string
                ville:
                  type: string
                emplacement:
                  type: string
                prix:
                  type: number
                  format: float
              type: object
      responses:
        '200':
          description: "Création d'un évènement"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Events'
  '/infrastructures/Api/Events/searchEvent.php?ville={ville}&date={edate}':
    get:
      tags:
        - Evenements
      summary: "La création d'un évènement"
      operationId: 310d0d9a39347760743df7e4847e997f
      parameters:
        -
          name: ville
          in: query
          description: "La ville qui abrite l'évènement"
          required: true
          schema:
            type: string
      responses:
        '200':
          description: "Recherche d'un évèvement a partir de la ville et la date"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Events'
  /infrastructures/Api/Users/createUser.php:
    post:
      tags:
        - Utilisateurs
      summary: "La création d'un utilisateur"
      operationId: 354cafa544f710308b22e7cfe763211b
      requestBody:
        content:
          multipart/form-data:
            schema:
              properties:
                nom:
                  type: string
                email:
                  type: string
                password:
                  type: string
              type: object
      responses:
        '200':
          description: "Création d'un utilisateur avec succès"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Users'
  /infrastructures/Api/Users/loginUser.php:
    post:
      tags:
        - Utilisateurs
      summary: "se connecter avec l'email et mot de passe"
      operationId: 82cfbfe1bd6fd201197aac93f6c764fe
      requestBody:
        content:
          multipart/form-data:
            schema:
              properties:
                email:
                  type: string
                password:
                  type: string
              type: object
      responses:
        '200':
          description: "Connexion de l'utilisateurr avec succès"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Users'
components:
  schemas:
    Booking:
      properties:
        user:
          type: string
        event:
          type: string
        nombreTicket:
          type: integer
        fullName:
          type: string
        email:
          type: string
        confirmation:
          type: integer
        uuid:
          type: string
        createdAt:
          type: string
          format: date-time
      type: object
    Events:
      properties:
        name:
          type: string
        edate:
          type: string
          format: date-time
        etime:
          type: string
          format: date-time
        emplacement:
          type: string
        ville:
          type: string
        prix:
          type: number
          format: float
        uuid:
          type: string
        createdAt:
          type: string
          format: date-time
      type: object
    Users:
      properties:
        nom:
          type: string
        email:
          type: string
        password:
          type: string
        uuid:
          type: string
        createdAt:
          type: string
          format: date-time
      type: object
  responses:
    '404':
      description: "Echec de la creation d'un utilisateur"
